### ISSUE TITLE
Allow user-loaded configurations in YAML format

### ISSUE THREAD

**Issue by signebedi** [signebedi/mercutio#2]
Before moving this package out of development and move to v1.0, I want to allow users to customize their user criteria (1) interactively or (2) with loaded configuration files.

I think that a YAML file makes sense for this. We can add a dependency for `pyyaml` and then allow the end user to pass an optional command link argument to include a configuration file. I'm not terribly experienced with YAML but here's an initial stab at the format of the configuration file:

```yaml
- proficiencies:
    - attributes:
        - strength
        - constitution
        - intelligence
        - wisdom
        - dexterity
        - charisma
    - skills:
        - athletics
        - acrobatics
        - sleight
        - stealth
        - arcana
        - history
        - investigation
        - nature
        - religion
        - animal-handling
        - insight
        - medicine
        - perception
        - survival
        - deception
        - intimidation
        - performance
        - persuasion 
   - armor: false
    - weapons: false
- buffs:
    - class:
        - fighter
        - wizard
        - rogue
        - cleric
    - race:
        - human
        - elf
        - wood elf
        - high elf
        - dark elf
        - dwarf
        - hill dwarf
        - mountain dwarf
        - halfling
        - stout halfling
        - lightfoot halfling
    - religion: false
    - language: false
    - background: 
```
The above values can even be turned off by the end user if they want, as is the case with `armor`, `weapons`, `religion`, and `language`. While there are common-sense limitations to how customizable this can be, I envision that v2.0 will allow the users to pass their own proficiency and buff categories.
